baseURL = "https://smyrgeorge.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "paper"

# website title
title = ":: exploration and stuff ::"
languageCode = 'en-us'

disqusShortname = 'smyrgeorge'   # use disqus comments

[params]
  # color style
  color = 'linen'                         # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'           # twitter.com/YOUR_TWITTER_ID
  github = 'smyrgeorge'                   # github.com/YOUR_GITHUB_ID
  instagram = 'smyrgeorge'                # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'smyrgeorge'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'       # e.g. 'https://mastodon.instance/@xxx'
  # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  rss = true                              # show rss icon

  # home page profile
  avatar = 'smyrgeorge@gmail.com'         # gravatar email or image url
  name = 'Yorgos S.'
  bio = 'Barcelona, Spain'

  # misc
  disableHLJS = false                             # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = false                           # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'  # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"        # use graph comment (disqus alternative)
  math = true
